### ISSUE TITLE
打包.app

### ISSUE THREAD

**Issue by popor** [imeiju/iMeiJu_Mac#1]
可以把打包好的app压缩包,直接放到release (https://github.com/imeiju/iMeiJu_Mac/releases) 里面吗?
这样就不用每次下载打包了.

**Comment by iptodays** [comment]
安排。从下个版本开始就这样做

**Comment by qinze118** [comment]
请问下大神如何打包app呀，不会用

**Comment by iizvv** [comment]
目前下载代码直接编译即可

**Comment by iptodays** [comment]
> 请问下大神如何打包app呀，不会用

目前下载代码后,直接编译便可使用

**Comment by qinze118** [comment]
本人mac小白，不知道如何编择操作，还望大神指教哈

**Comment by iptodays** [comment]
> 本人mac小白，不知道如何编择操作，还望大神指教哈

和iOS操作相同, 编译成功后,在Products文件夹下就可以找到可执行文件
![image](https://user-images.githubusercontent.com/15830996/56109632-ffe40980-5f83-11e9-8e88-5aec8db62441.png)

**Comment by qinze118** [comment]
好的，谢谢哈

**Comment by qinze118** [comment]
编译时找不到sqlite，本人不太会mac系统的开发哈，还请指教Controls/IZPlotMessageViewController.swift:12:8: error: no such module 'SQLite'
import SQLite
       ^

** BUILD FAILED **

**Comment by iptodays** [comment]
> 编译时找不到sqlite，本人不太会mac系统的开发哈，还请指教Controls/IZPlotMessageViewController.swift:12:8: error: no such module 'SQLite'
> import SQLite
> ^
> 
> ** BUILD FAILED **

我已经更新了pod, 现在使用了swift5, 你可以先update一下。然后再试一下

**Comment by qinze118** [comment]
恩，我重新clone下

**Comment by qinze118** [comment]
好像还报那个错。。。,找不到sqlite，我在我本上安装了一下，也不行。。

**Comment by iptodays** [comment]
这个是不需要本地安装sql的。你可以加我微信,
![F5F43226FF66D7F8A1791235B3AB41C7](https://user-images.githubusercontent.com/15830996/56123173-827dc080-5fa6-11e9-9562-9e421b2fa0ed.png)
