### ISSUE TITLE
意外退出

### ISSUE THREAD

**Issue by Sicmatr1x** [imeiju/iMeiJu_Mac#2]
```
Process:               iMeiJu_Mac [58424]
Path:                  /Volumes/VOLUME/*/iMeiJu.app/Contents/MacOS/iMeiJu_Mac
Identifier:            com.iizvv.iMeiJu-Mac
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           iMeiJu_Mac [58424]
User ID:               501

Date/Time:             2019-05-10 20:59:22.748 +0800
OS Version:            Mac OS X 10.13.6 (17G6030)
Report Version:        12
Anonymous UUID:        988E0EF7-3989-EE22-706A-583A3290C3AD

Sleep/Wake UUID:       45FB296F-54BB-48BC-8B26-1989C394B9C2

Time Awake Since Boot: 130000 seconds
Time Since Wake:       490 seconds

System Integrity Protection: disabled

Notes:                 Translocated Process

Crashed Thread:        0

Exception Type:        EXC_CRASH (Code Signature Invalid)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace CODESIGNING, Code 0x1

kernel messages:

VM Regions Near 0 (cr2):
--> 
    __TEXT                 0000000107eba000-0000000107f05000 [  300K] r-x/rwx SM=COW  

Thread 0 Crashed:
0   ???                           	0x000000011668619c _dyld_start + 0

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x0000000000000000  rsp: 0x00007ffee7d45b18
   r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000000
  r12: 0x0000000000000000  r13: 0x0000000000000000  r14: 0x0000000000000000  r15: 0x0000000000000000
  rip: 0x000000011668619c  rfl: 0x0000000000000200  cr2: 0x0000000000000000
  
Logical CPU:     0
Error Code:      0x00000000
Trap Number:     0


Binary Images:
       0x107eba000 -        0x107f04ff7 +??? (0) <497F44F6-FDB7-30B5-9944-B1581299AFE7> (null)
       0x116685000 -        0x1166cfacf +??? (551.5) <30B355CB-35BA-3112-AA76-4E46CD45F699> (null)

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 67241
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=1132K resident=0K(0%) swapped_out_or_unallocated=1132K(100%)
Writable regions: Total=8412K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=8412K(100%)
 
                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
STACK GUARD                       56.0M        2 
Stack                             8192K        2 
__DATA                             292K        5 
__LINKEDIT                         532K        3 
__TEXT                             600K        3 
shared memory                        8K        3 
===========                     =======  ======= 
TOTAL                             65.4M       12 
```

**Comment by iptodays** [comment]
> Process:               iMeiJu_Mac [58424]
> Path:                  /Volumes/VOLUME/*/iMeiJu.app/Contents/MacOS/iMeiJu_Mac
> Identifier:            com.iizvv.iMeiJu-Mac
> Version:               ???
> Code Type:             X86-64 (Native)
> Parent Process:        ??? [1]
> Responsible:           iMeiJu_Mac [58424]
> User ID:               501
> 
> Date/Time:             2019-05-10 20:59:22.748 +0800
> OS Version:            Mac OS X 10.13.6 (17G6030)
> Report Version:        12
> Anonymous UUID:        988E0EF7-3989-EE22-706A-583A3290C3AD
> 
> Sleep/Wake UUID:       45FB296F-54BB-48BC-8B26-1989C394B9C2
> 
> Time Awake Since Boot: 130000 seconds
> Time Since Wake:       490 seconds
> 
> System Integrity Protection: disabled
> 
> Notes:                 Translocated Process
> 
> Crashed Thread:        0
> 
> Exception Type:        EXC_CRASH (Code Signature Invalid)
> Exception Codes:       0x0000000000000000, 0x0000000000000000
> Exception Note:        EXC_CORPSE_NOTIFY
> 
> Termination Reason:    Namespace CODESIGNING, Code 0x1
> 
> kernel messages:
> 
> VM Regions Near 0 (cr2):
> --> 
>     __TEXT                 0000000107eba000-0000000107f05000 [  300K] r-x/rwx SM=COW  
> 
> Thread 0 Crashed:
> 0   ???                           	0x000000011668619c _dyld_start + 0
> 
> Thread 0 crashed with X86 Thread State (64-bit):
>   rax: 0x0000000000000000  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
>   rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x0000000000000000  rsp: 0x00007ffee7d45b18
>    r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000000
>   r12: 0x0000000000000000  r13: 0x0000000000000000  r14: 0x0000000000000000  r15: 0x0000000000000000
>   rip: 0x000000011668619c  rfl: 0x0000000000000200  cr2: 0x0000000000000000
>   
> Logical CPU:     0
> Error Code:      0x00000000
> Trap Number:     0
> 
> 
> Binary Images:
>        0x107eba000 -        0x107f04ff7 +??? (0) <497F44F6-FDB7-30B5-9944-B1581299AFE7> (null)
>        0x116685000 -        0x1166cfacf +??? (551.5) <30B355CB-35BA-3112-AA76-4E46CD45F699> (null)
> 
> External Modification Summary:
>   Calls made by other processes targeting this process:
>     task_for_pid: 0
>     thread_create: 0
>     thread_set_state: 0
>   Calls made by this process:
>     task_for_pid: 0
>     thread_create: 0
>     thread_set_state: 0
>   Calls made by all processes on this machine:
>     task_for_pid: 67241
>     thread_create: 0
>     thread_set_state: 0
> 
> VM Region Summary:
> ReadOnly portion of Libraries: Total=1132K resident=0K(0%) swapped_out_or_unallocated=1132K(100%)
> Writable regions: Total=8412K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=8412K(100%)
>  
>                                 VIRTUAL   REGION 
> REGION TYPE                        SIZE    COUNT (non-coalesced) 
> ===========                     =======  ======= 
> STACK GUARD                       56.0M        2 
> Stack                             8192K        2 
> __DATA                             292K        5 
> __LINKEDIT                         532K        3 
> __TEXT                             600K        3 
> shared memory                        8K        3 
> ===========                     =======  ======= 
> TOTAL                             65.4M       12

可以描述一下操作吗

**Comment by Sicmatr1x** [comment]
运行之后就提示错误

**Comment by iptodays** [comment]
> 运行之后就提示错误

现在是无法运行吗?重新编译一下呢,  有可能是证书过期的问题
